services:
  - type: web
    name: BlogManagementAPI
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        value: <your-mongo-db-connection-string>
      - key: JWT_SECRET
        value: <your-jwt-secret>
      - key: NODE_ENV
        value: production
